// This header is generated by zig from base64.zig (BUG: doesn't work in Zig 0.14.0-dev.1081+5d080e25d)
// #include "base64.h"
#include <stdint.h>

// workaround
extern size_t decode_base_64(
    uint8_t *dest_ptr,
    size_t dest_len,
    const uint8_t *source_ptr,
    size_t source_len
);

#include <string.h>
#include <stdio.h>

int main(int argc, char **argv) {
    const char *encoded = "YWxsIHlvdXIgYmFzZSBhcmUgYmVsb25nIHRvIHVz";
    char buf[200];

    size_t len = decode_base_64(buf, 200, encoded, strlen(encoded));
    buf[len] = 0;
    puts(buf);

    return 0;
}