// This header is generated by zig from base64.zig (BUG: doesn't work in Zig 0.14.0-dev.1081+5d080e25d)
// #include "base64.h"
#include <stdio.h>
#include <stdint.h>

extern int32_t add(int32_t a, int32_t b) {
    return a + b;
}

int main(int argc, char **argv) {
    int32_t result = add(42, 1337);
    printf("%d\n", result);
    return 0;
}